# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import servicios_pb2 as servicios__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in servicios_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class cliente_nameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.enviar_metadata = channel.unary_unary(
                '/cliente_name/enviar_metadata',
                request_serializer=servicios__pb2.informacion_archivo.SerializeToString,
                response_deserializer=servicios__pb2.metadata.FromString,
                _registered_method=True)
        self.pedir_metadata = channel.unary_unary(
                '/cliente_name/pedir_metadata',
                request_serializer=servicios__pb2.peticion.SerializeToString,
                response_deserializer=servicios__pb2.lista_bloques.FromString,
                _registered_method=True)


class cliente_nameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def enviar_metadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pedir_metadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cliente_nameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'enviar_metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.enviar_metadata,
                    request_deserializer=servicios__pb2.informacion_archivo.FromString,
                    response_serializer=servicios__pb2.metadata.SerializeToString,
            ),
            'pedir_metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.pedir_metadata,
                    request_deserializer=servicios__pb2.peticion.FromString,
                    response_serializer=servicios__pb2.lista_bloques.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cliente_name', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cliente_name', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class cliente_name(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def enviar_metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cliente_name/enviar_metadata',
            servicios__pb2.informacion_archivo.SerializeToString,
            servicios__pb2.metadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def pedir_metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cliente_name/pedir_metadata',
            servicios__pb2.peticion.SerializeToString,
            servicios__pb2.lista_bloques.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class cliente_dataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.enviar_bloques = channel.unary_unary(
                '/cliente_data/enviar_bloques',
                request_serializer=servicios__pb2.informacion_bloque.SerializeToString,
                response_deserializer=servicios__pb2.confirmacion.FromString,
                _registered_method=True)
        self.recibir_bloques = channel.unary_unary(
                '/cliente_data/recibir_bloques',
                request_serializer=servicios__pb2.peticion_bloque.SerializeToString,
                response_deserializer=servicios__pb2.respuesta_bloque.FromString,
                _registered_method=True)


class cliente_dataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def enviar_bloques(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def recibir_bloques(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cliente_dataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'enviar_bloques': grpc.unary_unary_rpc_method_handler(
                    servicer.enviar_bloques,
                    request_deserializer=servicios__pb2.informacion_bloque.FromString,
                    response_serializer=servicios__pb2.confirmacion.SerializeToString,
            ),
            'recibir_bloques': grpc.unary_unary_rpc_method_handler(
                    servicer.recibir_bloques,
                    request_deserializer=servicios__pb2.peticion_bloque.FromString,
                    response_serializer=servicios__pb2.respuesta_bloque.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cliente_data', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cliente_data', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class cliente_data(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def enviar_bloques(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cliente_data/enviar_bloques',
            servicios__pb2.informacion_bloque.SerializeToString,
            servicios__pb2.confirmacion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def recibir_bloques(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cliente_data/recibir_bloques',
            servicios__pb2.peticion_bloque.SerializeToString,
            servicios__pb2.respuesta_bloque.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
